#!/usr/bin/env python3
import os
import sys
import pprint
from pathlib import Path
from collections import OrderedDict

import yaml
import click


# Global constants
DEFAULT_CONFIG_PATH=os.path.expanduser("~/.anssh.yml")

# Helper functions
## Config parsing
def get_config(configfile=None):
    if configfile is None:
        configfile = open(DEFAULT_CONFIG_PATH, 'r')
    config = yaml.safe_load(configfile.read())
    if config is None:
        config = {}
    return config

def parse_hosts_node(node):
    parsed_nodes = dict()
    for node_item in node.items():
        if node_item[0] == 'children':
            if node_item[1] is not None:
                for subnode in node_item[1].items():
                    parsed_node_data = parse_hosts_node(subnode[1])
                    if parsed_nodes is None:
                        parsed_nodes = dict()
                    parsed_nodes.update(parsed_node_data)
        if node_item[0] == 'hosts':
            if node_item[1] is not None:
                for subnode in node_item[1].items():
                    temp_node = {
                        subnode[0]: {
                            'host': subnode[1].get('ansible_host', subnode[0]),
                            'port': subnode[1].get('ansible_port', None),
                            'user': subnode[1].get('ansible_user', None),
                            'ssh_key': subnode[1].get('ansible_ssh_private_key_file', None),
                            'options': subnode[1].get('ansible_ssh_common_args', None),
                            }
                        }
                    if temp_node[subnode[0]]['ssh_key'] is not None:
                        temp_node[subnode[0]]['ssh_key'] = os.path.expanduser(temp_node['ssh_key'])
                    parsed_nodes.update(temp_node)
    return parsed_nodes

def parse_hosts(hosts_file_dict):
    with open(hosts_file_dict['hosts_path']) as fil:
        hosts_file_data = yaml.safe_load(fil.read())
    parsed_data = parse_hosts_node(hosts_file_data['all'])
    # Merge with other data in hosts_file_dict
    for key, data in parsed_data.items():
        data['user'] = data['user'] if data['user'] is not None else hosts_file_dict['user']
        data['ssh_key'] = data['ssh_key'] if data['ssh_key'] is not None else hosts_file_dict['ssh_key']
        data['options'] = data['options'] if data['options'] is not None else hosts_file_dict['options']
        data['namespace'] = hosts_file_dict['namespace']
        data['client'] = hosts_file_dict['client']

    return parsed_data

def generate_hosts(config):
    hosts = dict()

    # Get default params from config if it present
    defaults = config.get('default', dict())
    if defaults is None:
        defaults = dict()

    # Per namespace, generate list of hosts files
    for namespace in config.get('namespaces', []):
        try:
            namespace_name = namespace['name']
        except Exception:
            click.echo("Namespace does not have name")
            pprint.pprint(namespace)
            sys.exit(1)

        hosts[namespace_name] = {}

        namespace_user = namespace.get('user', defaults.get('user', None)) # None will use system default
        namespace_ssh_key = namespace.get('ssh_key', defaults.get('ssh_key', None)) # Same
        namespace_options = namespace.get('options', defaults.get('options', None)) # Same
        if namespace_ssh_key is not None:
            namespace_ssh_key = os.path.expanduser(namespace_ssh_key)

        # Get list of hosts files from namespace `clients` key
        for client in namespace.get('clients', list()):
            try:
                client_name = client['name']
            except Exception:
                click.echo("Clientd does not have name")
                pprint.pprint(client)
                sys.exit(2)

            client_user = client.get('user', namespace_user)
            client_ssh_key = client.get('ssh_key', namespace_ssh_key)
            client_options = client.get('options', namespace_options)
            if client_ssh_key is not None:
                client_ssh_key = os.path.expanduser(client_ssh_key)
            client_hosts_path = client['hosts_path']

            hosts_parsed = parse_hosts({
                'user': client_user,
                'ssh_key': client_ssh_key,
                'options': client_options,
                'hosts_path': os.path.expanduser(client_hosts_path),
                'client': client_name,
                'namespace': namespace_name,
            })

            hosts[namespace_name][client_name] = dict()
            hosts[namespace_name][client_name].update(hosts_parsed)

        # Get list of hosts files from autodetect
        for auto_clients in namespace.get('autodetect_clients', list()):
            auto_clients_user = auto_clients.get('user', namespace_user)
            auto_clients_ssh_key = auto_clients.get('ssh_key', namespace_ssh_key)
            auto_clients_options = auto_clients.get('options', namespace_options)
            if auto_clients_ssh_key is not None:
                auto_clients_ssh_key = os.path.expanduser(auto_clients_ssh_key)

            auto_clients_root = auto_clients['inventories_path']
            auto_clients_hosts_filename = auto_clients['hosts_filename']

            # Get list of users in auto_clients_root by the name of dirs
            auto_clients_subdirs = next(os.walk(os.path.expanduser(auto_clients_root)))[1]
            for client_name in auto_clients_subdirs:
                client_hosts_path = os.path.join(auto_clients_root, client_name, auto_clients_hosts_filename)

                hosts_parsed = parse_hosts({
                    'user': auto_clients_user,
                    'ssh_key': auto_clients_ssh_key,
                    'options': auto_clients_options,
                    'hosts_path': os.path.expanduser(client_hosts_path),
                    'client': client_name,
                    'namespace': namespace_name,
                })

                hosts[namespace_name][client_name] = dict()
                hosts[namespace_name][client_name].update(hosts_parsed)

    return hosts

## Connection string generation
def generate_ssh_command(host_data):
    args = ['ssh']
    args = args + ([] if host_data['user'] is None else ['-l', host_data['user']])
    args = args + ([] if host_data['ssh_key'] is None else ['-i', host_data['ssh_key']])
    args = args + ([] if host_data['options'] is None else [host_data['options']])
    args = args + ([] if host_data['port'] is None else ['-p', str(host_data['port'])])
    args = args + [host_data['host']]
    return ' '.join(args)


## Autocompletion functions
# XXX usage of dynamic ctx is pretty much broken at the moment, so only default config will will work https://github.com/pallets/click/issues/942
def auto_get_namespaces(ctx, args, incomplete):
    try: 
        if ctx.obj is None:
            config = get_config()
        else:
            config = ctx.obj['config']

        namespaces_available = list(
                generate_hosts(
                    config
                ).keys()
            )

        namespaces = list()

        if len(incomplete) > 0:
            for namespace in  namespaces_available:
                if namespace.startswith(incomplete):
                    namespaces.append(namespace)
        else:
            namespaces = namespaces_available

        return sorted(namespaces)

    except KeyboardInterrupt:
        return []


def auto_get_clients(ctx, args, incomplete):
    try:
        if ctx.obj is None:
            config = get_config()
        else:
            config = ctx.obj['config']

        namespace = args[1]

        clients_available = list(
                generate_hosts(
                    config
                ).get(namespace, dict()).keys()
            )

        clients = list()

        if len(incomplete) > 0:
            for client in  clients_available:
                if client.startswith(incomplete):
                    clients.append(client)
        else:
            clients = clients_available

        return sorted(clients)

    except KeyboardInterrupt:
        return []

def auto_get_hosts(ctx, args, incomplete):
    try:
        if ctx.obj is None:
            config = get_config()
        else:
            config = ctx.obj['config']

        namespace = args[1]

        client = args[2]

        hosts_available = list(
                    generate_hosts(
                        config
                    ).get(namespace, dict()).get(client, dict()).keys()
                )

        hosts = list()

        if len(incomplete) > 0:
            for host in  hosts_available:
                if host.startswith(incomplete):
                    hosts.append(host)
        else:
            hosts = hosts_available

        return sorted(hosts)

    except KeyboardInterrupt:
        return []


# Click grouping
@click.group()
@click.pass_context
@click.option('--configfile', envvar='ANSSH_CONFIGFILE', default=DEFAULT_CONFIG_PATH, help='Path to config file', type=click.File('r'))
def cli(ctx, configfile):
    ctx.obj['config'] = get_config(configfile)

# Click commands
@cli.command()
@click.pass_context
def complete(ctx):
    script_path = os.path.realpath(__file__)

    click.echo("To add autocompletion, add this lines to ~/.bashrc:")
    click.echo("source <(_{}_COMPLETE=source {})".format(os.path.basename(__file__).upper(), script_path))

@cli.command()
@click.pass_context
def test_config(ctx):
    click.echo('Current dict of hosts files based on config:')
    hosts = generate_hosts(ctx.obj['config'])
    pprint.pprint(hosts)

@cli.command()
@click.pass_context
@click.argument('namespace', type=click.STRING, autocompletion=auto_get_namespaces)
def generate_apptmux_sessions_file(ctx, namespace):
    hosts_dict = generate_hosts(ctx.obj['config'])

    if namespace in hosts_dict:

        for client_name in sorted(hosts_dict[namespace].keys()):
            click.echo(client_name)

    else:
        click.echo("Namespace {} does not exist in config file".format(namespace))
        click.echo()
        click.echo("Available namespaces:")
        click.echo(', '.join(list(hosts_dict.keys())))
        sys.exit(1)

@cli.command()
@click.pass_context
@click.argument('namespace', type=click.STRING, autocompletion=auto_get_namespaces)
@click.argument('client', type=click.STRING, autocompletion=auto_get_clients)
def generate_apptmux_sessions_list(ctx, namespace, client):
    hosts_dict = generate_hosts(ctx.obj['config'])

    # Example - tmux new-window -n 'windy.database' -t Windy:1 'ssh -i ~/.ssh/my -p 22 ddunaev@5.9.6.115'
    if namespace in hosts_dict:

        if client in hosts_dict[namespace]:

                for host_name, host in hosts_dict[namespace][client].items():

                    host_number = list(hosts_dict[namespace][client].values()).index(host) + 1
                    ssh_command = generate_ssh_command(host)
                    click.echo("tmux new-window -n '{}' -t {}:{} '{}'".format(
                        host_name,
                        client,
                        host_number,
                        ssh_command,
                        )
                    )

        else:
            click.echo("Client {} in namepace {} does not exist in config file".format(client, namespace))
            click.echo()
            click.echo("Available clients in namespace {}:".format(namespace))
            click.echo(', '.join(list(hosts_dict[namespace].keys())))
            sys.exit(1)
    else:
        click.echo("Namespace {} does not exist in config file".format(namespace))
        click.echo()
        click.echo("Available namespaces:")
        click.echo(', '.join(list(hosts_dict.keys())))
        sys.exit(1)

@cli.command()
@click.pass_context
@click.argument('namespace', type=click.STRING, autocompletion=auto_get_namespaces)
@click.argument('client', type=click.STRING, autocompletion=auto_get_clients)
@click.argument('host', type=click.STRING, autocompletion=auto_get_hosts)
def connect(ctx, namespace, client, host):
    hosts = generate_hosts(
                ctx.obj['config']
            )
    host_data = hosts.get(namespace, dict()).get(client, dict()).get(host, None)
    if host_data is None:
        click.echo('Host not found')
    else:
        command = generate_ssh_command(host_data)
        click.echo(command)
        os.system(command)

if __name__ == "__main__":
    cli(obj={})
